2020-11-13 12:54:56,001 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:29]
2020-11-13 13:38:50,653 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:31]
2020-11-13 15:04:42,337 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:36]
2020-11-13 15:04:46,000 ERROR: Exception on /login [GET] [in /root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/flaskblog/app/routes.py", line 45, in login
    return render_template('login.html', title='Sign in', form=form)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/root/flaskblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/root/flaskblog/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/root/flaskblog/app/templates/login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/root/flaskblog/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/root/flaskblog/app/templates/base.html", line 54, in block "content"
    {% block app_content %}{% endblock %}
  File "/root/flaskblog/app/templates/login.html", line 16, in block "app_content"
    <a href="{{ url_for('reset_password_request') }}">Click to Reset It</a>
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/root/flaskblog/venv/lib/python3.9/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password_request'. Did you mean 'reset_password' instead?
2020-11-13 15:05:16,529 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:36]
2020-11-14 23:07:51,910 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:01:44,811 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:05:46,724 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:05:53,362 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:21:35,966 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:29:01,312 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:29:19,616 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:29:28,474 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:29:38,787 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:30:16,168 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:30:31,970 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:32:33,875 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:43:39,752 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:43:47,887 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:49:10,482 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:51:58,573 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:52:04,563 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 13:54:28,894 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:45]
2020-11-16 15:04:29,456 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:48]
2020-11-16 15:07:37,357 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:48]
2020-11-16 15:07:39,276 ERROR: Exception on /usr/susan [GET] [in /root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/root/flaskblog/app/routes.py", line 82, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/templating.py", line 137, in render_template
    return _render(
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/root/flaskblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/root/flaskblog/venv/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/root/flaskblog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/root/flaskblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 21, in block "body"
    {% block navbar %}
  File "/root/flaskblog/app/templates/base.html", line 17, in block "navbar"
    <a class="navbar-brand" href="{{ url_for('main.index') }}">Microblog</a>
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/app.py", line 2216, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/root/flaskblog/venv/lib/python3.9/site-packages/flask/helpers.py", line 357, in url_for
    rv = url_adapter.build(
  File "/root/flaskblog/venv/lib/python3.9/site-packages/werkzeug/routing.py", line 2179, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'main.index'. Did you mean 'index' instead?
2020-11-16 15:08:43,481 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:48]
2020-11-16 15:28:59,811 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:48]
2020-11-16 15:32:02,222 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:48]
2020-11-16 15:32:13,899 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:48]
2020-11-16 15:42:01,164 INFO: Microblog startup [in /root/flaskblog/app/__init__.py:48]
